CREATE TABLE IF NOT EXISTS FILM (
  REF_FILM VARCHAR(10) PRIMARY KEY NOT NULL,
  TITRE_FILM VARCHAR(80) NULL,
  CATEGORIE_FILM VARCHAR(31) NULL,
  STUDIO_FILM VARCHAR(65) NULL,
  DIRECTEUR_FILM VARCHAR(50) NULL,
  ANNEE_FILM INT(4) NULL
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS CASTS(
  	TITRE_FILM_CASTS VARCHAR(80) NULL,
	ACTEURS VARCHAR(40) NULL,
  	TYPE_ROLE VARCHAR(100) NULL,
	REF_FILM_CASTS VARCHAR(10),
  	FOREIGN KEY (REF_FILM_CASTS) REFERENCES FILM (REF_FILM)
) Engine=InnoDB DEFAULT CHARSET=utf8;
